name: argos_translator_offline
description: "A Flutter package to auto translate localization keys from .arb files. and .json file offline and free"
version: 0.0.2
homepage: https://github.com/abdoelmorap/argos_translatetor_offline
repository: https://github.com/abdoelmorap/argos_translatetor_offline
issue_tracker: https://github.com/abdoelmorap/argos_translatetor_offline/issues



environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.0
  path: ^1.8.0
assets:
  - dlls/argos_bridge.dll
screenshots:
  - description: The argos_translator_offline package logo.
    path: screenshots/logo.png
executables:
  argos_translate_dart: argos_translate_dart
dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
