name: argos_translator_offline
description: "A Flutter package to automated translate localization keys from .arb files. and .json file offline and free"
version: 1.2.0
homepage: https://github.com/abdoelmorap/argos_translate_dart_offline
repository: https://github.com/abdoelmorap/argos_translate_dart_offline
issue_tracker: https://github.com/abdoelmorap/argos_translate_dart_offline/issues



environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.0
  path: ^1.8.0
  package_config: ^2.1.0


assets:
  - dlls/argos_bridge.dll
screenshots:
  - description: The argos_translator_offline package logo.
    path: screenshots/logo.png

executables:
  argos_translator_offline: argos_translator_offline
dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
